### PR TITLE
Allow NaNs for MAD

### PR DESCRIPTION
**Pull request by ingonader**
### All Submissions Basics:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Have you checked all [Issues](../../issues) to tie the PR to a specific one?

### All Submissions Cores:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?
* [x] Does your submission pass tests, including CircleCI, Travis CI, and AppVeyor?
* [x] Does your submission have appropriate code coverage? The cutoff threshold is 95% by Coversall.

### Changes

Related Issue: https://github.com/yzhao062/pyod/issues/376

This PR aims to allow `np.NaN` and `np.infty` values in the MAD outlier detection method. The method as previously implemented seemes to have some functionality to deal with NaNs (using `np.nanmedian()` at least in some calculations), but the `check_array()` function, as currently parametrized, throws an error.

This PR uses `check_array()` with `force_all_finite=False` and also changes the calculation of `self.median_diff` in `_mad()` to `np.nanmedian()`. Hence, the model is no able to cope with missing and infinite values.

In addition, some of the existing tests have been added (based on existing tests with addition of missing and infinite values).

#### Have you successfully ran tests with your changes locally?

All tests for MAD (`python -m unittest pyod/test/test_mad.py`) ran successfully. However, out of the total test suite (`python -m unittest discover ./pyod/test/`), 5 tests failed. All of the failing tests are unrelated to MAD, and all of the failing tests are related to `keras`. I suspect this is some kind of local problem with my installation.

Gist from test logs:
```
ERROR: test_auto_encoder (unittest.loader._FailedTest)
ImportError: cannot import name 'tf2'
ERROR: test_deepsvdd (unittest.loader._FailedTest)
ModuleNotFoundError: DeepSVDD runs only with TensorFlow 2.0+
ERROR: test_mo_gaal (unittest.loader._FailedTest)
ImportError: cannot import name 'tf2'
ERROR: test_so_gaal (unittest.loader._FailedTest)
ImportError: cannot import name 'tf2'
ERROR: test_vae (unittest.loader._FailedTest)
ImportError: cannot import name 'tf2'
Ran 527 tests in 571.009s
FAILED (errors=5)
```

#### Does your submission pass tests, including CircleCI, Travis CI, and AppVeyor?

I have only tested via Travis CI, and I hope this does not pose a problem. In Travis, 4 of 5 build passed, but the
build für Python 3.3 failed when installing the requirements (which are unchanged in this PR). So I hope this is still fine.

Gist from Travis logs:
```
$ pip install -r requirements_ci.txt
Collecting combo
  Downloading combo-0.1.2.tar.gz (37 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  × python setup.py egg_info did not run successfully.
  [...]
        File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 886, in find_distributions
          found = self._search_paths(context.name, context.path)
      AttributeError: 'str' object has no attribute 'name'
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
```

### CODE REVIEW

**Comment by yzhao062** [comment]
since MAD was implemented by @John-Almardeny maybe it is helpful if he could take a quick check.

One minor thing:

- predict and score function is already depreacted; no need to modify base.py for it.

**Comment by John-Almardeny** [comment]
> since MAD was implemented by @John-Almardeny maybe it is helpful if he could take a quick check.
> 
> One minor thing:
> 
> * predict and score function is already depreacted; no need to modify base.py for it.

@yzhao062 
The MAD algorithm looks good to me. 
If you're okay with the changes in `base` and `utils`, then it's ready for merge.

**Comment by ingonader** [comment]
> One minor thing:
> predict and score function is already depreacted; no need to modify base.py for it.

Not sure what the status is. Does this mean that I should remove the changes I made, or can I just leave it as is, since it's deprecated anyway?

Is there anything you need me to do before merging?

**Comment by yzhao062** [comment]
maybe remove the changes for the base.py and I could merge the rest. thanks!

**Comment by ingonader** [comment]
I have removed the changes from `base.py`, and I have removed the tests that relied on these changes: `test_fit_predict_score_with_nan()` and `test_fit_predict_score_with_inf()`. There are still some tests left that test the the `predict()` function. They don't affect anything else except MAD, and they can be removed at a later stage when the deprecated functionality is removed from the package.

Unit tests have passed locally (with the same results as mentioned above), builds are in progress.

**Comment by yzhao062** [comment]
Thanks! It is merged now and will be in the next release!

**Comment by ingonader** [comment]
Great, thanks!

**Pull request merged**
