### PR TITLE
Pythresh Documentation

### PR DESCRIPTION
**Pull request by KulikDM**
### All Submissions Basics:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Have you checked all [Issues](../../issues) to tie the PR to a specific one?

### All Submissions Cores:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?
* [x] Does your submission pass tests, including CircleCI, Travis CI, and AppVeyor?
* [x] Does your submission have appropriate code coverage? The cutoff threshold is 95% by Coversall.

Update to PyOD documentation, accommodating for the addition of the PyThresh thresholding API. Also some small adjustments so that the thresholds match that found in the latest PyThresh release. Please make any changes that I may have missed or let me know and I'll handle them before the merge. Appreciated.

### CODE REVIEW

**Comment by KulikDM** [comment]
@yzhao062 Hi, I have made sure that this branch is up to date with the latest commits and should not have any conflicts. Hopefully this extra documentation will add to the benefit of PyOD.

**Comment by KulikDM** [comment]
Hi @yzhao062 hope all is well. Just wanted to know if there are any updates on this and the other new PRs?

**Comment by yzhao062** [comment]
Hi there,

Thanks for the PR! Would you mind updating this PR a bit to address the conflict? Sorry I remove the test file to test file for pythresh to turn off the error messages. Feel free to bring it back. Basically these three files should be slightly updated.

image


Thanks for your understanding!
Cheers,

Yue

**Comment by yzhao062** [comment]
Oh do not worry! I should be able to address that on my end :)

**Comment by KulikDM** [comment]
Hi @yzhao062 thanks for getting to this! I see that the Mac OS python 3.7 failed. I've seen it happening for the same reason on other packages as well recently. It's an environment thing. P.S Python 3.7's end of life is just around the corner. Perhaps updating to support 3.11 and removing 3.7? All the best ;)

**Pull request merged**
