### PR TITLE
LMDD Implementation

### LINKED ISSUE #92: Deviation-Based Outlier Detection (New Feature)
As far as I noticed that PyOD does not have any Deviation-Based Outlier Detection Type of Model.
Although, they are not very popular and relatively old, but I think it is nice to have a one in the collection.

----------------------------

### Linear Method for Deviation Detection for Large Databases
Based on the work of [Arning, A., Agrawal, R., and Raghavan, P. 1996. A linear method for deviation detection in large databases. In Proc. Int. Conf. on Knowledge Discovery and Data Mining (KDD), Portland, OR.](https://www.aaai.org/Papers/KDD/1996/KDD96-027.pdf) ; The Linear Method for Deviation-based Outlier Detection (LMDD) employs the concept of the Smoothing Factor (SF) which indicates how much the dissimilarity can be reduced by removing a subset of elements from the data-set.

The dissimilarity function can be any as per mentioned clearly in the paper. The one proposed in the paper is *the variance*, however, more options can be used from the Statistical Dispersion Measures. (Already implemented Average Absolute Deviation; Variance; and Interquartile Range, However, Median Absolute Deviation to be added in future once Scipy Stats Version 1.3.0 is released - *optional*).

The original algorithm outputs *Labels*, with a very minor tweak, it can output now *Scores*.

### PR DESCRIPTION
**Pull request by John-Almardeny**
### All Submissions Basics:
Closes #92 
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Have you checked all [Issues](../../issues) to tie the PR to a specific one?

### All Submissions Cores:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?
* [x] Does your submission pass tests, including CircleCI, Travis CI, and AppVeyor?
* [x] Does your submission have appropriate code coverage? The cutoff threshold is 95% by Coversall.

### New Model Submissions:

* [x] Have you created a <NewModel>.py in ~/pyod/models/?
* [x] Have you created a <NewModel>_example.py in ~/examples/?
* [x] Have you created a test_<NewModel>.py in ~/pyod/test/?
* [x] Have you lint your code locally prior to submission?

----------------------------------------

### Linear Method for Deviation Detection for Large Databases
Based on the work of [Arning, A., Agrawal, R., and Raghavan, P. 1996. A linear method for deviation detection in large databases. In Proc. Int. Conf. on Knowledge Discovery and Data Mining (KDD), Portland, OR.](https://www.aaai.org/Papers/KDD/1996/KDD96-027.pdf) ; The Linear Method for Deviation-based Outlier Detection (LMDD) employs the concept of the Smoothing Factor (SF) which indicates how much the dissimilarity can be reduced by removing a subset of elements from the data-set.

The dissimilarity function can be any as per mentioned clearly in the paper. The one proposed in the paper is *the variance*, however, more options can be used from the Statistical Dispersion Measures. (Already implemented Average Absolute Deviation; Variance; and Interquartile Range, However, Median Absolute Deviation to be added in future once Scipy Stats Version 1.3.0 is released).

The original algorithm outputs *Labels*, with a very minor tweak, it can output now *Scores*.

Side-Note: `aad` Dissimilarity Measure is giving better results in the simulations compared to `var` and even faster in execution.  I wonder if the authors of the paper tried all possible measures :D

[Cited by 515](https://scholar.google.com/scholar?cites=15465809453845193211&as_sdt=2005&sciodt=0,5&hl=en).

### CODE REVIEW

**Comment by John-Almardeny** [comment]
Hi Yue,

Here the same,
There is a problem in building your original `development` branch:

    ModuleNotFoundError: No module named 'sklearn.externals.funcsigs'

It seems that `python-sklearn` package is not installed after doing the updates.

**Comment by yzhao062** [comment]
It is caused by the update on sckit-learn. The latest one is 0.21. and sklearn.externals.funcsigs.py is removed. I need to figure out what is the best way to address this :(

**Comment by yzhao062** [comment]
the dev branch is fixed. will rebase master as well :)

**Comment by yzhao062** [comment]
Hey John. Sorry for being late on this. Thanks a lot for the implementation and it will be out in V0.7.6 soon (today or tomorrow). I was getting slow on clearing up the pip due to various research projects.

Wish you a happy 2020!

**Pull request merged**
