### PR TITLE
R-graph method implemented

### PR DESCRIPTION
**Pull request by mbongaerts**
R-graph

paper: 
[https://openaccess.thecvf.com/content_cvpr_2017/papers/You_Provable_Self-Representation_Based_CVPR_2017_paper.pdf](https://openaccess.thecvf.com/content_cvpr_2017/papers/You_Provable_Self-Representation_Based_CVPR_2017_paper.pdf)

### All Submissions Basics:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Have you checked all [Issues](../../issues) to tie the PR to a specific one?

### All Submissions Cores:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?
* [x] Does your submission pass tests, including CircleCI, Travis CI, and AppVeyor? 
* [ ] Does your submission have appropriate code coverage? The cutoff threshold is 95% by Coversall.

### New Model Submissions:

* [x] Have you created a <NewModel>.py in ~/pyod/models/?
* [x] Have you created a <NewModel>_example.py in ~/examples/?
* [x] Have you created a test_<NewModel>.py in ~/pyod/test/?
* [x] Have you lint your code locally prior to submission?

### CODE REVIEW

**Comment by yzhao062** [comment]
Thanks for checking. If you do not mind, please still finish as complete as possible. We will then read the paper and try to review. Thanks~

**Comment by mbongaerts** [comment]
> Thanks for checking. If you do not mind, please still finish as complete as possible. We will then read the paper and try to review. Thanks~

Everything looks fine now. I believe it ready to be pulled into the master. Thanks!

**Comment by mbongaerts** [comment]
Dear @yzhao062, 
This implementation is also ready to be merged into `development`. However, a weird error occurs now in the AppVeyor, which was previously not there. I think this error is on the AppVeyor side, and not the implementation (?).

**Comment by mbongaerts** [comment]
Except for coverage/coveralls, everything seems to work!

**Comment by yzhao062** [comment]
Hi, I started reviewing and updating this PR. Just wonder if you could point out the paper for it? I will build that in the documentation :)

**Comment by mbongaerts** [comment]
> Thanks for checking. If you do not mind, please still finish as complete as possible. We will then read the paper and try to review. Thanks~

Good to hear! This is the paper `https://openaccess.thecvf.com/content_cvpr_2017/papers/You_Provable_Self-Representation_Based_CVPR_2017_paper.pdf`

**Comment by yzhao062** [comment]
> > Thanks for checking. If you do not mind, please still finish as complete as possible. We will then read the paper and try to review. Thanks~
> 
> Good to hear! This is the paper https://openaccess.thecvf.com/content_cvpr_2017/papers/You_Provable_Self-Representation_Based_CVPR_2017_paper.pdf

Perfect. I will do it this afternoon and release in 1.0.4 :) thanks a lot!

**Pull request merged**
