### PR TITLE
Cooks distance branch

### PR DESCRIPTION
**Pull request by KulikD-proj**
Cook's distance outlier detector

A supervised regression outlier detector

Cook's distance can be used to identify points that negatively affect a regression model. A combination of each observation’s leverage and residual values are used in the measurement. Higher leverage and residuals relate to  higher Cook’s distances. Read more in the :cite:`cook1977outlier` --> https://www.jstor.org/stable/1268249

The script cd.py has been added to pyod/models/ containing the Cook's distance outlier detector. The code is mostly based off what has been implemented in the Yellowbrick repo but thought it would be nice to be able to call it with all the others outlier detectors in Pyod. 

Hopefully this will become an useful addition to the already great repo and python package that Pyod is.

### CODE REVIEW

**Comment by yzhao062** [comment]
Thanks for the PR, could you do a few things to make this a bit clear?

1. add an simple example file as [we have under /examples/knn_example.py](https://github.com/yzhao062/pyod/blob/master/examples/hbos_example.py)
2. if possible, add a unit test like this one very simple indeed https://github.com/yzhao062/pyod/blob/master/pyod/test/test_knn.py

I will take from there~btw, please submit the PR to the development branch.

Thanks again.

Yue

**Comment by yzhao062** [comment]
I think the code looks great. One last thing is the PR should be submitted to the development branch. Please resubmit in that way. Other than that, things look cool. Thanks a lot.

**Comment by KulikD-proj** [comment]
Excellent! Glad that this outlier detector can soon become another addition to this great package. Hopefully it has changed the PR to the Development branch

**Comment by yzhao062** [comment]
perfect. I will do a merge and some local edits. Thanks!

**Pull request merged**
