### PR TITLE
Implementing ECDF Estimator and deleting Statsmodels dependency

### PR DESCRIPTION
**Pull request by Lucew**
Hey everyone,

as stated in #466 and in #453, one can speed up the empirical cumulative density function in comparison to the Statsmodels [ECDF functionality](https://www.statsmodels.org/dev/generated/statsmodels.distributions.empirical_distribution.ECDF.html).

This also makes the dependency on statsmodels obsolete and this pull request deletes the dependency.

In this pull request the following things are done:
1) **Implementing an standalone ecdf estimator** in [pyod/utils/stat_models.py](https://github.com/Lucew/pyod/blob/development/pyod/utils/stat_models.py)
2) Writing a [test](https://github.com/Lucew/pyod/blob/development/pyod/test/test_stat_models.py) that compares own implementation to statsmodels implementation on several random matrices (so in the requirements_ci.txt statsmodels is still a requirement)
3) Deleting and replacing the functionality in [ECOD](https://github.com/Lucew/pyod/blob/development/pyod/models/ecod.py) and [COPOD](https://github.com/Lucew/pyod/blob/development/pyod/models/copod.py) (the only places this dependency has been used

The **implementation is now faster** (by 30-60%), as we will only use the ecdf for the data we estimate it from. Please get back to me if a further explanation of why exactly is necessary. I will gladly elaborate more.

Since not anyone might want to fully submerge in the topic, I kept the statsmodels dependency in the test and compare this implementation to the statsmodels function on several random matrices. One could see that as prove that it works.

Thanks in advance! :-)

--------

### All Submissions Basics:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Have you checked all [Issues](../../issues) to tie the PR to a specific one?

### All Submissions Cores:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?
* [x] Does your submission pass tests, including CircleCI, Travis CI, and AppVeyor?
* [x] Does your submission have appropriate code coverage? The cutoff threshold is 95% by Coversall.

### CODE REVIEW

**Comment by Lucew** [comment]
Just pushed an update to the parallel testing of ECOD and COPOD in order to increase the test coverage.

Unfortunately, I had to force a push in between as I already did some further changes to #453 on my development branch (my bad). Shifted those to an extra branch for now.

**Comment by yzhao062** [comment]
Thanks for the PR...I will try to get them in the next few weeks with some performance comparison with the original version :) Happy holidays!

**Comment by yzhao062** [comment]
Sorry for the delay! this looks great thank you so much!

**Comment by Lucew** [comment]
Hey, no worries. I know that life happens sometimes.

I'm glad I could contribute. Maybe there will be another PR sometime in the next weeks.

Hope you are not already tired of those :D

**Pull request merged**
