### PR TITLE
COF Algorithm

### LINKED ISSUE #7: implement Connectivity-based outlier factor (COF)
See https://dl.acm.org/citation.cfm?id=693665 for more information.

### PR DESCRIPTION
**Pull request by John-Almardeny**
### All Submissions Basics:
Closes #7 
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Have you checked all [Issues](../../issues) to tie the PR to a specific one?

### All Submissions Cores:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?
* [x] Does your submission pass tests, including CircleCI, Travis CI, and AppVeyor?
* [x] Does your submission have appropriate code coverage? The cutoff threshold is 95% by Coversall.

### New Model Submissions:

* [x] Have you created a <NewModel>.py in ~/pyod/models/?
* [x] Have you created a <NewModel>_example.py in ~/examples/?
* [x] Have you created a test_<NewModel>.py in ~/pyod/test/?
* [x] Have you lint your code locally prior to submission?

### CODE REVIEW

**Comment by John-Almardeny** [comment]
@yzhao062 

Hi Yue,
I am happy with it now. Please check and merge.
Related issue: Implement Connectivity-based outlier factor (COF) #7 
Thanks,
Yahya.

**Comment by yzhao062** [comment]
Hi Yahya,

By any chance could you make a new PR for the three files only?
cof.py, cof_example.py, and test_cof.py.

I mistakenly deleted requirements_ci.txt (which should not be touched) from this PR. Merging this may result in some difficulties.  If so I could close one and work on the new PR.

Thanks.
Yue

**Comment by John-Almardeny** [comment]
Hi Yue,

I do not know why ya deleted the file. You should have compared it with `development` branch because they he exact same :)   Previously, I just needed `pandas` so I added it then I found a way to get rid of `pandas`, thus I reverted my action. As a result, there's no change to `requirements_ci.txt` at all.

I will copy it from development and push it again to the branch. So there will be no problem.

**Comment by John-Almardeny** [comment]
Hi Yue,
Now this PR is identical to your `development` branch except the 3 files ya mentioned.
Cheers :)

**Comment by John-Almardeny** [comment]
Hi Yue,

There is a problem in building your original `development` branch:

    ModuleNotFoundError: No module named 'sklearn.externals.funcsigs'

It seems that `python-sklearn` package is not installed after doing the updates.

**Comment by yzhao062** [comment]
Thanks for implementing this model. It is merged now and will be out in V0.7.2. I will direct all COF related issues to you. I will also include it in benchmark and other visualization:) Thanks a lot for the patience!

Yue

**Pull request merged**
