### PR TITLE
added functionality for scoring the individual features for the COPOD…

### PR DESCRIPTION
**Pull request by psmgeelen**
… algorithm in copod.py. This includes the single threaded and multi-threaded implementation.

This should also resolve the issue https://github.com/yzhao062/pyod/issues/308

This is my first pull-request in a public repo, so please let me know whether I have included enough information.

### All Submissions Basics:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Have you checked all [Issues](../../issues) to tie the PR to a specific one?

### All Submissions Cores:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?
* [x] Does your submission pass tests, including CircleCI, Travis CI, and AppVeyor?
* [x] Does your submission have appropriate code coverage? The cutoff threshold is 95% by Coversall.

### CODE REVIEW

**Comment by psmgeelen** [comment]
It passed all checks but it didnt!?!?!?!

**Comment by psmgeelen** [comment]
@yzhao062 , I think it did pass all the tests, but for some reason its not showing as such..

**Comment by yzhao062** [comment]
This looks fine to me. Sorry for being late. Could you resubmit this to the development branch?

**Comment by psmgeelen** [comment]
Lets see what happens..

**Comment by psmgeelen** [comment]
@yzhao062 this should be good right? (my first pull request..)

**Comment by psmgeelen** [comment]
@yzhao062 ?

**Comment by yzhao062** [comment]
Hi there, you should submit it to the development branch.
image

like this one:
https://github.com/yzhao062/pyod/pull/318

Thanks!

**Comment by psmgeelen** [comment]
@yzhao062 , sorry for my late response, please review https://github.com/yzhao062/pyod/pull/361

**Pull request closed without merging**
