### PR TITLE
Switch from (pure) keras based on tensorflow to the keras loaded from the tensorflow library

### PR DESCRIPTION
**Pull request by sekerjak**
### All Submissions Basics:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Have you checked all [Issues](../../issues) to tie the PR to a specific one?

### All Submissions Cores:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?

According to the https://keras.io/ I think, that that's good idea to switch from pure keras to keras loaded from tensorflow:

### Multi-backend Keras and tf.keras:
At this time, we recommend that Keras users who use multi-backend Keras with the TensorFlow backend switch to tf.keras in TensorFlow 2.0. tf.keras is better maintained and has better integration with TensorFlow features (eager execution, distribution support and other).

Keras 2.2.5 was the last release of Keras implementing the 2.2.* API. It was the last release to only support TensorFlow 1 (as well as Theano and CNTK).

The current release is Keras 2.3.0, which makes significant API changes and add support for TensorFlow 2.0. The 2.3.0 release will be the last major release of multi-backend Keras. Multi-backend Keras is superseded by tf.keras.

Bugs present in multi-backend Keras will only be fixed until April 2020 (as part of minor releases).

For more information about the future of Keras, see the Keras meeting notes

### CODE REVIEW

**Comment by yzhao062** [comment]
thanks for the note. could you do a search and also fix the ones with so_gaal and mo_gaal. Thanks,

I will add the note to deprecate the use of keras and then gradually retire it by replacing with tf.

Thanks again.

**Comment by sekerjak** [comment]
Hey,

I did changes (keras -> tensorflow.keras) in other files + I changed the URLs, which pointed to keras.io to proper URLs -> tensorflow.org

**Comment by sekerjak** [comment]
@yzhao062 Any update on this pull request? I want to use the PyOD framework in my diploma thesis and it will be nice to have this change in the official release (of course I can change it locally), but this change can help me a little bit :)

**Comment by yzhao062** [comment]
> @yzhao062 Any update on this pull request? I want to use the PyOD framework in my diploma thesis and it will be nice to have this change in the official release (of course I can change it locally), but this change can help me a little bit :)

I will aim to close it by this month in the next major release 0.7.6.  I will get much more time to be back on this after next Thursday as the semester ends. You are always welcome to say it will be in in your thesis...

**Comment by yzhao062** [comment]
Hi there, I read through the keras documentation today and notice this will be TF 2.0 feature, although it has been out since TF 1.5. As the best practice, I will have to first send deprecation warnings the users before fully replace it. 
Which means this PR will not be closed in a few weeks, if not months. But I am good with your code will merge it for sure. and you are welcome to put this on your thesis/resume as you asked :) Merging it and be on the master will take some time though. Thanks for the understanding!

Yue

**Comment by yzhao062** [comment]
Hi there, we finally decided to write more complex if/else check to decide how to import keras. thanks for the effort and there is no issue of putting this on your thesis/resume. Best wishes!

**Pull request closed without merging**
