### PR TITLE
DistanceMetric hotfix

### PR DESCRIPTION
**Pull request by KulikDM**
### All Submissions Basics:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Have you checked all [Issues](../../issues) to tie the PR to a specific one?

### All Submissions Cores:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?
* [ ] Does your submission pass tests, including CircleCI, Travis CI, and AppVeyor?
* [ ] Does your submission have appropriate code coverage? The cutoff threshold is 95% by Coversall.

This is a hot fix for `sklearn's DistanceMetric`, an alternative to this PR and maybe perhaps better is to up the minimum `sklearn` version to 1.0.0 and change the `DistanceMetric` to the new API.

### CODE REVIEW

**Comment by yzhao062** [comment]
Hi @KulikDM :) the newer version of scikit-learn -> 1.3.0 appears to cause many problems. 
I have fixed others and the only failed tests now is test_threshold.py (see test results here). Would you mind taking a look to see what is might be the problem?

Cheers,
Yue

**Comment by KulikDM** [comment]
Hi @yzhao062, `scikit-learn=1.3.0` has caused a real change up to a lot of packages. The issue in `test_threshold.py` is a single test cause to an external library `scikit-lego` which I helped address in [PR 562](https://github.com/koaning/scikit-lego/pull/562). However, `sckit-lego` is currently having other issues with the new `scikit-learn` version and can't create a new release [Issue 564](https://github.com/koaning/scikit-lego/issues/564). If you temporarily replace scikit-lego with https://github.com/koaning/scikit-lego/archive/main.zip in the `requirement-ci.txt` file `test_threshold.py` should pass. Otherwise, `META` could also be removed from `test_threshold.py` but that is a bit more of an extreme step. Let me know what you think should be done and I'll try to keep you posted on any updates from my side.

Best,
Daniel

**Comment by yzhao062** [comment]
Thanks for the thought! In that sense let us wait for the refresh of scikit-lego :)

**Comment by KulikDM** [comment]
Hi @yzhao062 just finished helping to get `scikit-lego` working and I see that `test_threshold.py` is now passing all the tests :)

**Comment by yzhao062** [comment]
that is great!

**Pull request closed without merging**
