### PR TITLE
QMCD detector

### PR DESCRIPTION
**Pull request by KulikDM**
### All Submissions Basics:

* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
* [x] Have you checked all [Issues](../../issues) to tie the PR to a specific one?

### All Submissions Cores:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your core changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?
* [x] Does your submission pass tests, including CircleCI, Travis CI, and AppVeyor?
* [x] Does your submission have appropriate code coverage? The cutoff threshold is 95% by Coversall.

### New Model Submissions:

* [x] Have you created a <NewModel>.py in ~/pyod/models/?
* [x] Have you created a <NewModel>_example.py in ~/examples/?
* [x] Have you created a test_<NewModel>.py in ~/pyod/test/?
* [x] Have you lint your code locally prior to submission?

### Description
Quasi-Monte Carlo Discrepancy outlier detection
ref: https://www.sciencedirect.com/science/article/pii/S0885064X01905898

The Wrap-around Quasi-Monte Carlo discrepancy is a uniformity criterion which is used to assess the space filling of a number of samples in a hypercube. It quantifies the distance between the continuous uniform distribution on a hypercube and the discrete uniform distribution on distinct sample points. Therefore, lower discrepancy values for a sample point indicates that it provides better coverage of the parameter space with regards to the rest of the samples. This method is kernel based and the a higher discrepancy score is relative to the rest of the samples, the higher the likelihood of it being an outlier.

### CODE REVIEW

**Comment by yzhao062** [comment]
Will come back to this soon!

**Comment by KulikDM** [comment]
Hi @yzhao062 I just wanted to find out how is it going with this and all the other new pull requests? Much appreciated.

**Comment by yzhao062** [comment]
sorry for the delay. I am in the process of PhD graduation and job hunting...can be extremely behind for these few months :(

**Comment by yzhao062** [comment]
thanks for the PR could you provide the citation for this paper?

**Comment by yzhao062** [comment]
Sorry I saw the link now

**Pull request merged**
